# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f616156fc8957a96fc4d042dff0e28e4b996fe3388df82810a4a8f015bb050ea80f4c186c8d2f9c1a3676ebb67bf085437ba8568f0b9763000482c6c776e1e0

test:
  secret_key_base: f87c56228abc2ad946dd75140b51b24da911ec6227fa81aa09f54c078676fe90515d409b17c790fea4e691617f38c39ab4980958902cbf4ea97c242502993ed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
